apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: butter-service
    version: 0.0.1
  name: butter-service
  namespace: container-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: butter-service
      version: 0.0.1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: butter-service
        version: 0.0.1
      name: butter-service
    spec:
      containers:
      - name: butter-service
        env:
        - name: PORT
          value: "3000"
        image: docker-registry-dev.impdir.com/container-demo/butter-service:0.0.1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          timeoutSeconds: 1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
