apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-frontend
    version: 0.0.1
  name: demo-frontend
  namespace: container-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-frontend
      version: 0.0.1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-frontend
        version: 0.0.1
      name: demo-frontend
    spec:
      containers:
      - name: demo-frontend
        env:
        - name: PORT
          value: "3000"
        image: docker-registry-dev.impdir.com/container-demo/demo-frontend:0.0.3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          timeoutSeconds: 1
