apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-gateway
    version: 1.11.6-1
  name: demo-gateway
  namespace: container-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-gateway
      version: 1.11.6-1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-gateway
        version: 1.11.6-1
      name: demo-gateway
    spec:
      containers:
      - name: demo-gateway
        image: docker-registry-dev.impdir.com/container-demo/demo-gateway:0.0.1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          timeoutSeconds: 1
